# Generated by Django 5.2.10 on 2026-01-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cliente', models.CharField(max_length=11, verbose_name='CPF do Cliente')),
                ('produto', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('valor_encomenda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'Pix'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('DINHEIRO', 'Dinheiro')], max_length=20, verbose_name='Forma de Pagamento')),
                ('data_pedido', models.DateField(auto_now_add=True)),
                ('data_entrega', models.DateField()),
            ],
        ),
    ]
