# Generated by Django 5.2.10 on 2026-01-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0002_remove_endereco_complemento_endereco_complemento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='rua',
        ),
        migrations.AddField(
            model_name='endereco',
            name='endereco_descricao',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
