# Generated by Django 5.2.10 on 2026-01-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0003_remove_endereco_bairro_remove_endereco_cep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='endereco_descricao',
        ),
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='cep',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='estado',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='numero',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='rua',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
