# Generated by Django 6.0.1 on 2026-01-28 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('enderecos', '0004_remove_endereco_endereco_descricao_endereco_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='clientes.cliente'),
        ),
    ]
